[build]
publish = "dist"
command = "pnpm build"

[[redirects]]
from = "/api/*"
to = "https://api.openai.com/v1/:splat"
status = 200
force = true
headers = { X-From = "Netlify" }

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
Access-Control-Max-Age = "86400"

[[headers]]
for = "/api/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
Access-Control-Max-Age = "86400"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
